# 第二章 预备知识
## 2.1 数据操作
张量表示一个数值组成的数组，arange创建等差数组

In [1]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

用shape属性来访问张量的形状和张量中元素总数

In [2]:
x.shape

torch.Size([12])

In [3]:
x.numel()

12

In [4]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0、全1、或者其他常量或从特定分布中随机采样的数字,这里((2,3,4))表示三维数组，三维是2，二维是3，一维是4

In [5]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

通过提供包含的数值的python列表来为所需张量中的每个元素赋予确定的值（二维数组）

In [9]:
torch.tensor([[2,1,3,4],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

打印shape是一个三维的数组

In [12]:
torch.tensor([[[2,1,3,4],[1,2,3,4],[4,3,2,1]]]).shape

torch.Size([1, 3, 4])

常见的标准算数运算+ - * / ** （都是按元素分别进行计算）

In [14]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y # x**y进行的是求幂的运算 x的y次幂

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

按元素，每个元素子元素进行运算，以下是求e的x次方，表示方法，因为e的2次方=7.3891，说一7.3891e+00的意思就是7.3891*10的0次方。

In [15]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

把多个张量结合到一起，dim=0是按行堆在一起，dim=1是按列堆在一起
dim的取值范围由输入张量的维度决定，输入为n维张量，dim取值在[0,n-1]，dim=0时是在最高维度进行拼接，dim=1是在次最高维度进行拼接。

cat中din的学习链接：https://blog.csdn.net/m0_60105894/article/details/128311630

In [26]:
X = torch.arange(12,dtype=torch.float32).reshape(3,4) # X是3行4列二维数组
Y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

即使形状不同，我们仍然可以通过调用广播机制来执行按元素的操作

In [27]:
a = torch.arange(3).reshape([3,1])
b = torch.arange(2).reshape([1,2])
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

a+b是默认将两个矩阵都扩展成3*2的矩阵
a=[[0,0],[1,1],[2,2]]  b=[[0,1],[0,1],[0,1]]

In [28]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

可以用[-1]选择最后一个元素，用[1:3]选择第二和第三个元素

In [33]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5., 91.,  7.],
         [ 8.,  9., 10., 11.]]))

可以通过指定索引将元素写入矩阵

In [30]:
X[1,2] = 91# 将第1行第2列的值改成91
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 91.,  7.],
        [ 8.,  9., 10., 11.]])

运行一些操作可能导致为新结果分配内存

In [37]:
before = id(Y)
Y = Y + X
id(Y) == before

False

执行原地操作

In [40]:
Z = torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:] = X + Y# 对z进行改写，仍在原来内存处
print('id(Z):',id(Z))

id(Z): 2922724803104
id(Z): 2922724803104


如果在后续计算中没有重复使用X，我们也可以使用X[:] = X+Y 或 X += Y来减少操作的内存开销

In [41]:
before = id(X)
X += Y
id(X) == before

True

转换为Numpy张量

In [42]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为python标量,用.item()

In [46]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)